--1
CREATE TABLE TB_CATEGORY(
    NAME VARCHAR2(10),
    USE_YN CHAR(3) DEFAULT 'Y'
);
--2
CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10)
);
--3
ALTER TABLE TB_CATEGORY ADD PRIMARY KEY(NAME);
--4
ALTER TABLE TB_CLASS_TYPE MODIFY NAME NOT NULL;
--5
ALTER TABLE TB_CATEGORY MODIFY NAME VARCHAR2(20);
ALTER TABLE TB_CLASS_TYPE MODIFY NAME VARCHAR2(20);
ALTER TABLE TB_CLASS_TYPE MODIFY NO VARCHAR2(10);
--6
ALTER TABLE TB_CATEGORY RENAME COLUMN NAME TO CATEGORY_NAME;
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NAME TO CLASS_TYPE_NAME;
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NO TO CLASS_TYPE_NO;
--7
ALTER TABLE TB_CLASS_TYPE RENAME CONSTRAINT SYS_C007302 TO PK_CLASS_TYPE_NO;
ALTER TABLE TB_CATEGORY RENAME CONSTRAINT SYS_C007303 TO PK_CATEGORY_NAME;
--8
INSERT INTO TB_CATEGORY VALUES ('공학','Y');
INSERT INTO TB_CATEGORY VALUES ('자연과학','Y');
INSERT INTO TB_CATEGORY VALUES ('의학','Y');
INSERT INTO TB_CATEGORY VALUES ('예체능','Y');
INSERT INTO TB_CATEGORY VALUES ('인문사회','Y');
COMMIT;
--9
CREATE TABLE TB_DEPARTMENT1(
    CATEGORY VARCHAR2(10) CONSTRAINT FK_DEPARTMENT_CATEGORY REFERENCES TB_CATEGORY
);
--10
--GRANT CREATE VIEW TO WH;
CREATE OR REPLACE VIEW VW_SERCH_STUDENT
AS SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
    FROM TB_STUDENT;
--11    
CREATE OR REPLACE VIEW VW_CONSULTANT_LIST
AS SELECT STUDENT_NAME, DEPARTMENT_NAME, PROFESSOR_NAME
    FROM TB_STUDENT
    JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
    JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO);

SELECT * FROM VW_CONSULTANT_LIST;
--12
CREATE OR REPLACE VIEW VW_STU_SUM
AS SELECT DEPARTMENT_NAME, COUNT(DEPARTMENT_NO) AS "학과별합"
    FROM TB_DEPARTMENT
    JOIN TB_STUDENT USING (DEPARTMENT_NO)
    GROUP BY DEPARTMENT_NAME
    ORDER BY COUNT(DEPARTMENT_NO);
--13
UPDATE VW_SERCH_STUDENT
SET STUDENT_NAME = '윤승희'
WHERE STUDENT_NO = 'A213046';

SELECT * FROM TB_STUDENT WHERE STUDENT_NO = 'A213046';

--14
CREATE OR REPLACE VIEW VW_SERCH_STUDENT
AS SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
    FROM TB_STUDENT
WITH READ ONLY;
--이렇게 WITH READ ONLY를 써서 읽기만 가능하게 설정해준다

--15 잘 모르겠어요
SELECT CLASS_NO, CLASS_NAME, 
         COUNT(STUDENT_NO) AS "학과별합"
FROM TB_GRADE
ORDER BY TB_GRADE DESC
WHERE ROWNUM <= 3;
    
